# Generated by Django 3.0.7 on 2020-06-30 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200630_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='competition',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Competition'),
        ),
    ]
