# Generated by Django 3.0.7 on 2020-07-02 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200630_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='competition',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Competition'),
        ),
    ]
